version: "3.8"

services:
    app:
        container_name: e-commerce-api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "4000:3000"
        environment:
            - NODE_ENV=production
        restart: unless-stopped

    app-dev:
        container_name: e-commerce-api-dev
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - .:/app 
            - /app/node_modules
        environment:
            - NODE_ENV=development
        command: npm run dev
