version: "3.8"

services:
    app:
        container_name: e-commerce-api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - db
        env_file:
            - .env
        restart: unless-stopped

    app-dev:
        container_name: e-commerce-api-dev
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            - /app/node_modules
        env_file:
            - .env
        command: npm run dev

    db:
        container_name: postgres_db
        image: postgres:17
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        ports:
            - "5432:5432"
        volumes:
            - e_commerce_api_pg_data:/var/lib/postgresql/data
        restart: unless-stopped

    dbmate:
        image: amacneil/dbmate:2
        container_name: dbmate_migrations
        depends_on:
            - db
        environment:
            DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?sslmode=disable
        volumes:
            - ./src/lib/db/migrations:/db/migrations
        entrypoint: ["dbmate"]
        command: ["--help"]


volumes:
    e_commerce_api_pg_data:
