version: "3.8"

services:
    app:
        container_name: e-commerce-api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - db
        env_file:
            - .env
        restart: unless-stopped

    app-dev:
        container_name: e-commerce-api-dev
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            - /app/node_modules
        env_file:
            - .env
        command: npm run dev

    db:
        container_name: postgres_db
        image: postgres:17
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - e_commerce_api_pg_data:/var/lib/postgresql/data
        restart: unless-stopped

volumes:
    e_commerce_api_pg_data:
